services:
  - type: web
    name: youtube-download-api
    env: python
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COOKIES_FILE
        value: cookies.txt
